### ISSUE TITLE
EXC_BAD_ACCESS in FieldHeightSizingLayout.relayout()

### ISSUE THREAD

**Issue by mtancock** [radianttap/Fields#1]
This seems really cool. Thanks for publishing and the article you wrote with it.

I'm trying out the demo app (under iOS 13 on an iPhone XR simulator - not sure if that's an issue) and getting repeated crashes when it is trying to call `relayout()` in `FieldHeightSizingLayout`

The line in particular is 195:
`let	sectionCount = cv.numberOfSections`

If I try to scroll down past the category icons on the Signup form, it crashes every time, but I also have gotten the same crash when moving around generally.

Any ideas? Let me know if I can provide additional info

**Comment by radianttap** [comment]
Thanks for reporting. I have not yet tried this on iOS 13, it's a good nudge to check that out.

**Comment by radianttap** [comment]
Explained in the commit, should be working fine now.
